name: Translate Docs
description: Translate md files under docs folder.
author: Francisco Roldan
inputs:
  github-token:
    description: "GitHub Token"
    required: true
branding:
  icon: alert-circle
  color: blue
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up credentials
      shell: bash
      run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install google-cloud-translate
        pip install gitpython
        pip install PyGithub

    - name: Translate Markdown files
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_BASE_REF: ${{ secrets.GITHUB_SHA }}
        GITHUB_REF: ${{ secrets.GITHUB_REF }}
      run: |
        python ${{ github.action_path }}/src/translate_docs.py ${{ github.workspace }})

    - name: Remove credentials file
      shell: bash
      run: rm credentials.json